# -*- coding: utf-8 -*-
"""app1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CzUNeYsj7Dltd2GsrgevALZoNy_cVVEw
"""

import streamlit as st
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.sequence import pad_sequences

#

# Function to predict emotion


# Streamlit app



model = load_model('emotion_model.keras')  # Replace 'emotion_model.h5' with your model file

def predict_emotion(tweet):
    padded_seq = pad_sequences(get_sequences(tokenizer, [tweet]), maxlen=50)
    prediction = model.predict(padded_seq)
    emotion_class = tf.argmax(prediction, axis=1).numpy()[0]
    return emotion_class

def main():
    st.title("Emotion Prediction App")

    # Input text box
    user_input = st.text_area("Enter your tweet:", "")

    # Button to make predictions
    if st.button("Predict Emotion"):
        if user_input:
            emotion_class = predict_emotion(user_input)
            st.success(f"The predicted emotion class is: {emotion_class}")

if __name__ == "__main__":
    main()





